### ISSUE TITLE
NeoForwarding Problem with ATM 10

### ISSUE THREAD

**Issue by MarkapToGo** [Sonic2423/NeoForwarding#10]
I used the NeoForwarding mod on my ATm 10 servers and since version 1.0 you can no longer join the server if Neoforwarding mod is installed! 

Error on Server: 
_com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@72083fd8
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.AvailableCommandsPacket Direction CLIENTBOUND Protocol 1.21 State PLAY ID 11_

Error on Client: 
![image](https://github.com/user-attachments/assets/21f00200-c3b2-4d63-9524-98bbb0e8a207)

**Comment by manugame** [comment]
Logs from velocity for this issue

[latest.log](https://github.com/user-attachments/files/17368831/latest.log)

**Comment by LevyWilson** [comment]
I'm having the same issue. 
[latest.log](https://github.com/user-attachments/files/17393042/latest.log)

**Comment by LevyWilson** [comment]
I've discovered the problem. Disabling Living Things mod lets me connect. Some kind of incompatibility there.

**Comment by p0t4t0sandwich** [comment]
Living Things registers it's command argument to the vanilla registry, so the regular method of checking whether an argument needs to be wrapped/crosstiched doesn't end up working, because the key isn't null.

Actually, that's not how you check it in yours, not really sure why yours isn't working.

**Comment by p0t4t0sandwich** [comment]
Figured it out, the argument causing the issue is `minecraft:entity`, but only when Living Things is installed

**Comment by Sonic2423** [comment]
Fixed in next build. will be out in a couple of minutes. Velocity-436 and ATM10.1 with neoforge 21.1.71.

I haven´t tested extensively but the commands with auto completion seem to work fine.
![grafik](https://github.com/user-attachments/assets/f0cb7ea2-7ff0-48b5-b3ee-3774c62f02df)
(there is a lion from living things in the background to confirm it works)

**Comment by MarkapToGo** [comment]
I tried it with ATM 10 1.1 and the new NeoForwarding version and i still get the error!
Client disconnect log: https://mclo.gs/0ivPJec

Without NeoForwarding installed on the server, it works seamlessly...

**Comment by Sonic2423** [comment]
Please specify your exact setup:

**Comment by Sonic2423** [comment]
It seems the issue i fixed was another thing.

Please configure your velocity connection correctly and follow their basic setup (https://docs.papermc.io/velocity/getting-started#configuring-your-servers).

This error only pops up if you directly connect to the server and still have online-mode set to true in server.properties. You should connect through velocity. make sure you dont mix up your ports.

You can NOT directly connect to a server with NeoForwarding installed (That is the whole point of a proxy).

This error pops up because the commands packet it receives is intended for velocity. the packet contains all vanilla commands and everything else wrapped as a "crossstitch command" which the client can not decode.

I guess i should update my mod to show the user to connect with velocity if they try to connect directly to the server with online mode falsely set to true.

Let me know if that fixes your issue.

**Comment by MarkapToGo** [comment]
Velocity error: https://mclo.gs/P0Yzbaq
Error on the ATM Server (1.1): https://mclo.gs/gphBtOk
Backend Server in offline mode (also tried in online-mode)...
And I join over the velocity server with teh newest NeoForwarding Mod!

**Comment by Sonic2423** [comment]
The basic velocity setup requires you to set Player Info forwarding in velocity.toml to "modern". Your backend Server must be online-mode=false.

**Comment by MarkapToGo** [comment]
I have player-info-forwarding-mode = "modern" and the  backend servers on online-mode=false

**Comment by p0t4t0sandwich** [comment]
And you copied the velocity secret to the neoforwarding config?

**Comment by MarkapToGo** [comment]
Yes...

**Comment by Sonic2423** [comment]
is CrossStitch support enabled in the neoforwarding-server config?

**Comment by MarkapToGo** [comment]
yes

**Comment by Sonic2423** [comment]
is your game client/modpack updated? in log https://mclo.gs/0ivPJec it shows it is using neoforge version 21.1.69 which is not used by ATM10-1.1 or ATM10-1.0. maybe a clean instance solves the problem.

**Comment by MarkapToGo** [comment]
Yes I use the newer version and it’s the problem as described above…

**Comment by Sonic2423** [comment]
You stated earlier that if neoforwarding is not installed you could connect through velocity without issues? that should be impossible because neoforge even without any mods installed adds custom game test commands which must be wrapped to utilise velocitys builtin command wrapping. 

Have you created a test instance for the reasons stated before? yes the mods are there but the neoforge version is "wrong".

I can not reproduce this error. It would be greatly appreciated if you could share the exact steps to follow to reproduce this error. I want to see this working even if it is not directly caused by neoforwarding :). You may also overlook more errors in your velocity log because if you have multiple entries in the [try] section in velocity.toml it automatically tries every server in that list in the given order until one works and if none work the client usually spits out only the last disconnect message. make sure to not mix up your backend servers and/or use a forced host.

My working setup is as follows:

Proxy:
Download newest velocity.
run and stop for generation of config files.
in velocity.toml player-info-forwarding-mode = "modern" and in [servers] set lobby to "backendserver_ip_or_address:mcserver_port". the port should ideally not be 25565 for your backend servers.
take note of the bind address at the top of velocity.toml as there will be the port you will connect to from your minecraft client. newer versions of velocity will default to 25565!
run velocity with (as you are using windows):
java -jar "-Dvelocity.max-known-packs=400" "-Dvelocity.packet-decode-logging=true" velocity.jar

Server:
Download ATM10_1.1ServerFiles and just run (startserver.bat).
after accepting the eula just run again.
when the server has fully loaded then stop and ctrl+c to stop the auto restart.
in server.properties set online-mode=false and set the port to your mcserver_port. 
download and place neoforwarding in the mods directory.
run and stop the server again.
in the config folder open neoforwarding-server.toml and insert the forwarding.secret contained in the velocity directory.
run the server.

Client:
(as you are using atlauncher)
search for atm10 1.1 and click install. for the name i chose atm10_1.1_test and version 1.1 of course.
follow the install procedure.
run this instance.
add server with "velocity_ip_or_address:velocity_bind_port".
connect.
works.

![1](https://github.com/user-attachments/assets/16ea7688-bd38-4218-ae3c-543f16c51665)

![2](https://github.com/user-attachments/assets/aad9ec9e-c186-4052-af2e-d1435f1c4f0a)

Multiple servers also work as intended. i have a couple containers running different 1.20 and 1.21 servers and they all work just fine. forced hosts and server hopping with "/velocity serverX" works too.
